# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dae/Veridian-Zenith/SvaklaAI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dae/Veridian-Zenith/SvaklaAI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dae/Veridian-Zenith/SvaklaAI/CMakeFiles /home/dae/Veridian-Zenith/SvaklaAI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dae/Veridian-Zenith/SvaklaAI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SvaklaAI

# Build rule for target.
SvaklaAI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SvaklaAI
.PHONY : SvaklaAI

# fast build rule for target.
SvaklaAI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/build
.PHONY : SvaklaAI/fast

#=============================================================================
# Target rules for targets named api

# Build rule for target.
api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 api
.PHONY : api

# fast build rule for target.
api/fast:
	$(MAKE) $(MAKESILENT) -f api/CMakeFiles/api.dir/build.make api/CMakeFiles/api.dir/build
.PHONY : api/fast

#=============================================================================
# Target rules for targets named chat

# Build rule for target.
chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chat
.PHONY : chat

# fast build rule for target.
chat/fast:
	$(MAKE) $(MAKESILENT) -f chat/CMakeFiles/chat.dir/build.make chat/CMakeFiles/chat.dir/build
.PHONY : chat/fast

#=============================================================================
# Target rules for targets named ethics

# Build rule for target.
ethics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ethics
.PHONY : ethics

# fast build rule for target.
ethics/fast:
	$(MAKE) $(MAKESILENT) -f ethics/CMakeFiles/ethics.dir/build.make ethics/CMakeFiles/ethics.dir/build
.PHONY : ethics/fast

#=============================================================================
# Target rules for targets named list

# Build rule for target.
list: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 list
.PHONY : list

# fast build rule for target.
list/fast:
	$(MAKE) $(MAKESILENT) -f list/CMakeFiles/list.dir/build.make list/CMakeFiles/list.dir/build
.PHONY : list/fast

#=============================================================================
# Target rules for targets named logic

# Build rule for target.
logic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logic
.PHONY : logic

# fast build rule for target.
logic/fast:
	$(MAKE) $(MAKESILENT) -f logic/CMakeFiles/logic.dir/build.make logic/CMakeFiles/logic.dir/build
.PHONY : logic/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) $(MAKESILENT) -f model/CMakeFiles/model.dir/build.make model/CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named nlp

# Build rule for target.
nlp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nlp
.PHONY : nlp

# fast build rule for target.
nlp/fast:
	$(MAKE) $(MAKESILENT) -f nlp/CMakeFiles/nlp.dir/build.make nlp/CMakeFiles/nlp.dir/build
.PHONY : nlp/fast

#=============================================================================
# Target rules for targets named plugins

# Build rule for target.
plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 plugins
.PHONY : plugins

# fast build rule for target.
plugins/fast:
	$(MAKE) $(MAKESILENT) -f plugins/CMakeFiles/plugins.dir/build.make plugins/CMakeFiles/plugins.dir/build
.PHONY : plugins/fast

#=============================================================================
# Target rules for targets named programming

# Build rule for target.
programming: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 programming
.PHONY : programming

# fast build rule for target.
programming/fast:
	$(MAKE) $(MAKESILENT) -f programming/CMakeFiles/programming.dir/build.make programming/CMakeFiles/programming.dir/build
.PHONY : programming/fast

#=============================================================================
# Target rules for targets named scraping

# Build rule for target.
scraping: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scraping
.PHONY : scraping

# fast build rule for target.
scraping/fast:
	$(MAKE) $(MAKESILENT) -f scraping/CMakeFiles/scraping.dir/build.make scraping/CMakeFiles/scraping.dir/build
.PHONY : scraping/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named web_interface

# Build rule for target.
web_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 web_interface
.PHONY : web_interface

# fast build rule for target.
web_interface/fast:
	$(MAKE) $(MAKESILENT) -f web_interface/CMakeFiles/web_interface.dir/build.make web_interface/CMakeFiles/web_interface.dir/build
.PHONY : web_interface/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/main.cpp.s
.PHONY : main.cpp.s

src/advanced_low_level.o: src/advanced_low_level.cpp.o
.PHONY : src/advanced_low_level.o

# target to build an object file
src/advanced_low_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/advanced_low_level.cpp.o
.PHONY : src/advanced_low_level.cpp.o

src/advanced_low_level.i: src/advanced_low_level.cpp.i
.PHONY : src/advanced_low_level.i

# target to preprocess a source file
src/advanced_low_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/advanced_low_level.cpp.i
.PHONY : src/advanced_low_level.cpp.i

src/advanced_low_level.s: src/advanced_low_level.cpp.s
.PHONY : src/advanced_low_level.s

# target to generate assembly for a file
src/advanced_low_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/advanced_low_level.cpp.s
.PHONY : src/advanced_low_level.cpp.s

src/ai_core.o: src/ai_core.cpp.o
.PHONY : src/ai_core.o

# target to build an object file
src/ai_core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/ai_core.cpp.o
.PHONY : src/ai_core.cpp.o

src/ai_core.i: src/ai_core.cpp.i
.PHONY : src/ai_core.i

# target to preprocess a source file
src/ai_core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/ai_core.cpp.i
.PHONY : src/ai_core.cpp.i

src/ai_core.s: src/ai_core.cpp.s
.PHONY : src/ai_core.s

# target to generate assembly for a file
src/ai_core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/ai_core.cpp.s
.PHONY : src/ai_core.cpp.s

src/api_server.o: src/api_server.cpp.o
.PHONY : src/api_server.o

# target to build an object file
src/api_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/api_server.cpp.o
.PHONY : src/api_server.cpp.o

src/api_server.i: src/api_server.cpp.i
.PHONY : src/api_server.i

# target to preprocess a source file
src/api_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/api_server.cpp.i
.PHONY : src/api_server.cpp.i

src/api_server.s: src/api_server.cpp.s
.PHONY : src/api_server.s

# target to generate assembly for a file
src/api_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/api_server.cpp.s
.PHONY : src/api_server.cpp.s

src/auth.o: src/auth.cpp.o
.PHONY : src/auth.o

# target to build an object file
src/auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/auth.cpp.o
.PHONY : src/auth.cpp.o

src/auth.i: src/auth.cpp.i
.PHONY : src/auth.i

# target to preprocess a source file
src/auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/auth.cpp.i
.PHONY : src/auth.cpp.i

src/auth.s: src/auth.cpp.s
.PHONY : src/auth.s

# target to generate assembly for a file
src/auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/auth.cpp.s
.PHONY : src/auth.cpp.s

src/expansion_modules.o: src/expansion_modules.cpp.o
.PHONY : src/expansion_modules.o

# target to build an object file
src/expansion_modules.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/expansion_modules.cpp.o
.PHONY : src/expansion_modules.cpp.o

src/expansion_modules.i: src/expansion_modules.cpp.i
.PHONY : src/expansion_modules.i

# target to preprocess a source file
src/expansion_modules.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/expansion_modules.cpp.i
.PHONY : src/expansion_modules.cpp.i

src/expansion_modules.s: src/expansion_modules.cpp.s
.PHONY : src/expansion_modules.s

# target to generate assembly for a file
src/expansion_modules.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/expansion_modules.cpp.s
.PHONY : src/expansion_modules.cpp.s

src/external_service_interface.o: src/external_service_interface.cpp.o
.PHONY : src/external_service_interface.o

# target to build an object file
src/external_service_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/external_service_interface.cpp.o
.PHONY : src/external_service_interface.cpp.o

src/external_service_interface.i: src/external_service_interface.cpp.i
.PHONY : src/external_service_interface.i

# target to preprocess a source file
src/external_service_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/external_service_interface.cpp.i
.PHONY : src/external_service_interface.cpp.i

src/external_service_interface.s: src/external_service_interface.cpp.s
.PHONY : src/external_service_interface.s

# target to generate assembly for a file
src/external_service_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/external_service_interface.cpp.s
.PHONY : src/external_service_interface.cpp.s

src/final_summary.o: src/final_summary.cpp.o
.PHONY : src/final_summary.o

# target to build an object file
src/final_summary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/final_summary.cpp.o
.PHONY : src/final_summary.cpp.o

src/final_summary.i: src/final_summary.cpp.i
.PHONY : src/final_summary.i

# target to preprocess a source file
src/final_summary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/final_summary.cpp.i
.PHONY : src/final_summary.cpp.i

src/final_summary.s: src/final_summary.cpp.s
.PHONY : src/final_summary.s

# target to generate assembly for a file
src/final_summary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/final_summary.cpp.s
.PHONY : src/final_summary.cpp.s

src/http_server.o: src/http_server.cpp.o
.PHONY : src/http_server.o

# target to build an object file
src/http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/http_server.cpp.o
.PHONY : src/http_server.cpp.o

src/http_server.i: src/http_server.cpp.i
.PHONY : src/http_server.i

# target to preprocess a source file
src/http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/http_server.cpp.i
.PHONY : src/http_server.cpp.i

src/http_server.s: src/http_server.cpp.s
.PHONY : src/http_server.s

# target to generate assembly for a file
src/http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/http_server.cpp.s
.PHONY : src/http_server.cpp.s

src/installation_system.o: src/installation_system.cpp.o
.PHONY : src/installation_system.o

# target to build an object file
src/installation_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/installation_system.cpp.o
.PHONY : src/installation_system.cpp.o

src/installation_system.i: src/installation_system.cpp.i
.PHONY : src/installation_system.i

# target to preprocess a source file
src/installation_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/installation_system.cpp.i
.PHONY : src/installation_system.cpp.i

src/installation_system.s: src/installation_system.cpp.s
.PHONY : src/installation_system.s

# target to generate assembly for a file
src/installation_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/installation_system.cpp.s
.PHONY : src/installation_system.cpp.s

src/interactive_shell.o: src/interactive_shell.cpp.o
.PHONY : src/interactive_shell.o

# target to build an object file
src/interactive_shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/interactive_shell.cpp.o
.PHONY : src/interactive_shell.cpp.o

src/interactive_shell.i: src/interactive_shell.cpp.i
.PHONY : src/interactive_shell.i

# target to preprocess a source file
src/interactive_shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/interactive_shell.cpp.i
.PHONY : src/interactive_shell.cpp.i

src/interactive_shell.s: src/interactive_shell.cpp.s
.PHONY : src/interactive_shell.s

# target to generate assembly for a file
src/interactive_shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/interactive_shell.cpp.s
.PHONY : src/interactive_shell.cpp.s

src/local_memory_storage.o: src/local_memory_storage.cpp.o
.PHONY : src/local_memory_storage.o

# target to build an object file
src/local_memory_storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/local_memory_storage.cpp.o
.PHONY : src/local_memory_storage.cpp.o

src/local_memory_storage.i: src/local_memory_storage.cpp.i
.PHONY : src/local_memory_storage.i

# target to preprocess a source file
src/local_memory_storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/local_memory_storage.cpp.i
.PHONY : src/local_memory_storage.cpp.i

src/local_memory_storage.s: src/local_memory_storage.cpp.s
.PHONY : src/local_memory_storage.s

# target to generate assembly for a file
src/local_memory_storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/local_memory_storage.cpp.s
.PHONY : src/local_memory_storage.cpp.s

src/monitoring_safety.o: src/monitoring_safety.cpp.o
.PHONY : src/monitoring_safety.o

# target to build an object file
src/monitoring_safety.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/monitoring_safety.cpp.o
.PHONY : src/monitoring_safety.cpp.o

src/monitoring_safety.i: src/monitoring_safety.cpp.i
.PHONY : src/monitoring_safety.i

# target to preprocess a source file
src/monitoring_safety.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/monitoring_safety.cpp.i
.PHONY : src/monitoring_safety.cpp.i

src/monitoring_safety.s: src/monitoring_safety.cpp.s
.PHONY : src/monitoring_safety.s

# target to generate assembly for a file
src/monitoring_safety.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/monitoring_safety.cpp.s
.PHONY : src/monitoring_safety.cpp.s

src/plugin_system.o: src/plugin_system.cpp.o
.PHONY : src/plugin_system.o

# target to build an object file
src/plugin_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/plugin_system.cpp.o
.PHONY : src/plugin_system.cpp.o

src/plugin_system.i: src/plugin_system.cpp.i
.PHONY : src/plugin_system.i

# target to preprocess a source file
src/plugin_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/plugin_system.cpp.i
.PHONY : src/plugin_system.cpp.i

src/plugin_system.s: src/plugin_system.cpp.s
.PHONY : src/plugin_system.s

# target to generate assembly for a file
src/plugin_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/plugin_system.cpp.s
.PHONY : src/plugin_system.cpp.s

src/privacy_security.o: src/privacy_security.cpp.o
.PHONY : src/privacy_security.o

# target to build an object file
src/privacy_security.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/privacy_security.cpp.o
.PHONY : src/privacy_security.cpp.o

src/privacy_security.i: src/privacy_security.cpp.i
.PHONY : src/privacy_security.i

# target to preprocess a source file
src/privacy_security.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/privacy_security.cpp.i
.PHONY : src/privacy_security.cpp.i

src/privacy_security.s: src/privacy_security.cpp.s
.PHONY : src/privacy_security.s

# target to generate assembly for a file
src/privacy_security.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/privacy_security.cpp.s
.PHONY : src/privacy_security.cpp.s

src/web_interface.o: src/web_interface.cpp.o
.PHONY : src/web_interface.o

# target to build an object file
src/web_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/web_interface.cpp.o
.PHONY : src/web_interface.cpp.o

src/web_interface.i: src/web_interface.cpp.i
.PHONY : src/web_interface.i

# target to preprocess a source file
src/web_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/web_interface.cpp.i
.PHONY : src/web_interface.cpp.i

src/web_interface.s: src/web_interface.cpp.s
.PHONY : src/web_interface.s

# target to generate assembly for a file
src/web_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/web_interface.cpp.s
.PHONY : src/web_interface.cpp.s

src/websocket_server.o: src/websocket_server.cpp.o
.PHONY : src/websocket_server.o

# target to build an object file
src/websocket_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/websocket_server.cpp.o
.PHONY : src/websocket_server.cpp.o

src/websocket_server.i: src/websocket_server.cpp.i
.PHONY : src/websocket_server.i

# target to preprocess a source file
src/websocket_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/websocket_server.cpp.i
.PHONY : src/websocket_server.cpp.i

src/websocket_server.s: src/websocket_server.cpp.s
.PHONY : src/websocket_server.s

# target to generate assembly for a file
src/websocket_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SvaklaAI.dir/build.make CMakeFiles/SvaklaAI.dir/src/websocket_server.cpp.s
.PHONY : src/websocket_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SvaklaAI"
	@echo "... api"
	@echo "... chat"
	@echo "... ethics"
	@echo "... list"
	@echo "... logic"
	@echo "... model"
	@echo "... nlp"
	@echo "... plugins"
	@echo "... programming"
	@echo "... scraping"
	@echo "... tests"
	@echo "... web_interface"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/advanced_low_level.o"
	@echo "... src/advanced_low_level.i"
	@echo "... src/advanced_low_level.s"
	@echo "... src/ai_core.o"
	@echo "... src/ai_core.i"
	@echo "... src/ai_core.s"
	@echo "... src/api_server.o"
	@echo "... src/api_server.i"
	@echo "... src/api_server.s"
	@echo "... src/auth.o"
	@echo "... src/auth.i"
	@echo "... src/auth.s"
	@echo "... src/expansion_modules.o"
	@echo "... src/expansion_modules.i"
	@echo "... src/expansion_modules.s"
	@echo "... src/external_service_interface.o"
	@echo "... src/external_service_interface.i"
	@echo "... src/external_service_interface.s"
	@echo "... src/final_summary.o"
	@echo "... src/final_summary.i"
	@echo "... src/final_summary.s"
	@echo "... src/http_server.o"
	@echo "... src/http_server.i"
	@echo "... src/http_server.s"
	@echo "... src/installation_system.o"
	@echo "... src/installation_system.i"
	@echo "... src/installation_system.s"
	@echo "... src/interactive_shell.o"
	@echo "... src/interactive_shell.i"
	@echo "... src/interactive_shell.s"
	@echo "... src/local_memory_storage.o"
	@echo "... src/local_memory_storage.i"
	@echo "... src/local_memory_storage.s"
	@echo "... src/monitoring_safety.o"
	@echo "... src/monitoring_safety.i"
	@echo "... src/monitoring_safety.s"
	@echo "... src/plugin_system.o"
	@echo "... src/plugin_system.i"
	@echo "... src/plugin_system.s"
	@echo "... src/privacy_security.o"
	@echo "... src/privacy_security.i"
	@echo "... src/privacy_security.s"
	@echo "... src/web_interface.o"
	@echo "... src/web_interface.i"
	@echo "... src/web_interface.s"
	@echo "... src/websocket_server.o"
	@echo "... src/websocket_server.i"
	@echo "... src/websocket_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

